using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EulerSolutionsConsole.Solutions
{
    class _2_EvenFibonacciNumbers : Solution
    {
        public static string Description
        {
            get
            {
                return @"Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.";
            }
        }

        public override int GetValue()
        {
            int t1 = 1, t2 = 2;
            int sum = 0;
            int temp;

            while (t2 < 4000000)
            {
                if (t2 % 2 == 0)
                    sum += t2;

                temp = t2;
                t2 = t1 + t2;
                t1 = temp;
            }

            return sum;
        }
    }
}
